##
[Grid]
X1-grid    1  1.99      1  u  2.01
X2-grid    1  -0.0125      1  u  0.0125
X3-grid    1  -0.3  256    u  0.3

[TimeIntegrator]
CFL         0.5
tstop       200
first_dt    1.0e-5
fixed_dt    1.0e-3
nstages     2

[Hydro]
solver    hllc
csiso     userdef
# viscosity    explicit  userdef

# [Dust]
# nSpecies         0
# drag             userdef  1e-3    # St=1, 0.2, 0.04
# drag_feedback    no

[Particles]
count            per_proc  1
stopping_time    size  1e1

[Gravity]
potential    central 
Mcentral     1.0

[Boundary]
X1-beg    periodic
X1-end    periodic
X2-beg    periodic
X2-end    periodic
X3-beg    userdef
X3-end    userdef

[Setup]
sigma0        1
sigmaSlope    -0.5
CsSlope       -0.5
h0            0.05

[Output]
uservar    cs
vtk    1
dmp    1000.0
log        1000
dmp_dir    /home/dfang/Code/idefix_setups/VerticalSettling/outputs/Settling_Size_10_clean
vtk_dir    /home/dfang/Code/idefix_setups/VerticalSettling/outputs/Settling_Size_10_clean/vtks

# File produced automatically by a Perl script
# Do not edit
