##
[Grid]
X1-grid    1  1.99      1  u  2.01
X2-grid    1  -0.0125      1  u  0.0125
X3-grid    1  -0.3  512    u  0.3

[TimeIntegrator]
CFL         0.5
tstop       20
first_dt    1.0e-5
nstages     2

[Hydro]
solver    hllc
csiso     userdef
# viscosity    explicit  userdef

[Dust]
nSpecies         3
drag             userdef  1   0.2   0.04    # St=1, 0.2, 0.04
drag_feedback    no

[Particles]
count            per_proc  1
stopping_time    constant  1.0
ParticleMass     3e-3
DustToGas        3e-3

[Gravity]
potential    central 
Mcentral     1.0

[Boundary]
X1-beg    userdef
X1-end    userdef
X2-beg    periodic
X2-end    periodic
X3-beg    userdef
X3-end    userdef

[Setup]
sigma0        0.125
sigmaSlope    -0.5
CsSlope       -0.5
h0            0.05
alpha         1.0e-4

[Output]
vtk    0.1
dmp    1000.0
log        1000
dmp_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/VerticalSettling/outputs/SettlingL_Tau
vtk_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/VerticalSettling/outputs/SettlingL_Tau/vtks
# File produced automatically by a Perl script
# Do not edit
