##
[Grid]
X1-grid    1  1.0  1000  l   20.0
X2-grid    3  0.0  417   u  1.28   96  u  1.861592653589  417  u  3.141592653589793
# X2-grid    1  0.0  1024  u  3.141592653589793

[TimeIntegrator]
CFL            0.9
tstop          10000000.0
# tstop            1000.0
first_dt       1.e-6
nstages        2
max_runtime    0.495

[Hydro]
solver       hllc
csiso          constant 1.0

[Particles]
count            per_proc  1
stopping_time    constant  1.0
DustToGas        0.01
ParticleMass     1e-3
# gamma_i = 1/(rho beta_i) where beta_i is the given value

[Gravity]
potential    central
Mcentral     1.0

[Boundary]
X1-beg    outflow
X1-end    outflow
X2-beg    axis
X2-end    axis

[Setup]
sigmaSlope    0.5
csSlope       1.0
h0            0.05
alpha         1.0e-4

[Output]
vtk        1
dmp_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/L_DriftSettling/outputs/lDS_test
dmp        40
log        1000
vtk_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/L_DriftSettling/outputs/lDS_test/vtks
# dat_path   /home/dp316/dp316/dc-fang1/IdefixRuns/L_DriftSettling/outputs/lDS_test/timevol.dat
# analysis   1

# [Output]
#
# dmp        100
# vtk        3.0
# vtk_slice1 1.0  1  0.0  cut
# vtk_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/L_DriftSettling/outputs/lDS_test/vtks
# File produced automatically by a Perl script
# Do not edit
