##
[Grid]
X1-grid    1  0.4      128  u  2.5
X2-grid    1  1.2707963267948965  128   u  1.8707963267948966

# X3-grid    1  -0.0125  1    u  0.0125

[TimeIntegrator]
CFL         0.8
tstop       100
first_dt    1.0e-6
nstages     2

[Hydro]
solver    hllc
csiso     userdef
# viscosity    explicit  userdef

[Dust]
nSpecies         1
drag             tau  1    # St=1, 0.2, 0.04
drag_feedback    false


# [Particles]
# count            per_proc  1
# stopping_time    constant 1


[Gravity]
potential    central 
Mcentral     1.0

[Boundary]
X1-beg    userdef
X1-end    userdef
X2-beg    userdef
X2-end    outflow
# X3-beg    periodic
# X3-end    periodic

[Setup]
sigma0        0.125
sigmaSlope    -0.5
CsSlope       -0.5
h0            0.05

[Output]
uservar    cs
vtk    5.0
dmp    100.0
log        1000
dmp_dir    /home/dfang/Code/idefix_setups/DriftSettling/outputs/Drift_Tau
vtk_dir    /home/dfang/Code/idefix_setups/DriftSettling/outputs/Drift_Tau/vtks