##
[Grid]
X1-grid    1  1.0  1000  l   20.0
X2-grid    1  1.0471975511965976 512 u 2.0943951023931953 # [pi/3, 2pi/3]
# X2-grid    1  0.0  1024  u  3.141592653589793

[TimeIntegrator]
CFL            0.9
tstop          10000000.0
# tstop            1000.0
first_dt       1.e-6
nstages        2
max_runtime    0.495

[Hydro]
solver       hllc
csiso         userdef
viscosity   rkl userdef
alpha         1.0e-4

# [Dust]
# nSpecies         3
# drag              tau  1 0.2 0.04
# drag_feedback    false
# DustToGas        0.01
# gamma_i = 1/(rho beta_i) where beta_i is the given value

[Gravity]
potential    central
Mcentral     1.0

[Boundary]
X1-beg    outflow
X1-end    outflow
X2-beg    reflective
X2-end    reflective

[Setup]
sigma0        0.125
sigmaSlope    0.5
csSlope       1.0
h0            0.05

[Output]
vtk        1
dmp_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/DriftSettling/outputs/DS_test_reflective_viscous_alpha1e-4
dmp        40
log        1000
vtk_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/DriftSettling/outputs/DS_test_reflective_viscous_alpha1e-4/vtks
# dat_path   /home/dp316/dp316/dc-fang1/IdefixRuns/DriftSettling/outputs/DS_test_reflective_viscous_alpha1e-4/timevol.dat
# analysis   1

# [Output]
#
# dmp        100
# vtk        3.0
# vtk_slice1 1.0  1  0.0  cut
# vtk_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/DriftSettling/outputs/DS_test_reflective_viscous_alpha1e-4/vtks
# File produced automatically by a Perl script
# Do not edit
