##
[Grid]
X1-grid    1    -0.5   2048   u    0.5
X2-grid    1  -0.0125      1  u  0.0125
X3-grid    1  -0.0125  1    u  0.0125

[TimeIntegrator]
CFL              0.8
CFL_max_var      1.1
tstop            20
first_dt         1.e-4
nstages          2

[Hydro]
solver    hllc
csiso          constant 1.0
rotation       1.0
shearingBox    -1.5

[Gravity]
bodyForce      userdef

[Dust]
nSpecies         1
drag             userdef   0.1    # tau
drag_feedback    no

[Particles]
count            per_proc  1
stopping_time    userdef
ParticleMass     1e-3
tau              1e-1


[Boundary]
X1-beg        shearingbox
X1-end        shearingbox
#X2-beg    periodic
#X2-end    periodic
#X3-beg    outflow
#X3-end    outflow

[Setup]
Sigma0      1
n           1

[Output]
vtk    0.02
dmp    100.0
log        1000
dmp_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/MyDustyWave/outputs/dwave_n1
vtk_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/MyDustyWave/outputs/dwave_n1/vtks
# File produced automatically by a Perl script
# Do not edit
