##
[Grid]
X1-grid    1    -0.5   1024   u    0.5
X2-grid    1  -0.0125      1  u  0.0125
X3-grid    1  -0.0125  1    u  0.0125

[TimeIntegrator]
CFL              0.8
CFL_max_var      1.1
tstop            130
first_dt         1.e-4
nstages          2

[Hydro]
solver    hllc
csiso          constant 1.0
rotation       1.0
shearingBox    -1.5

[Gravity]
bodyForce      userdef

# [Dust]
# nSpecies         3
# drag             tau  1   0.2   0.04    # St=1, 0.2, 0.04
# drag_feedback    no

#[Particles]
#count            per_proc  3
#stopping_time    userdef
#ParticleMass     3e-3
#DustToGas        3e-3
#fields_real      size
## fields_real      t_stop


[Boundary]
X1-beg        shearingbox
X1-end        shearingbox
#X2-beg    periodic
#X2-end    periodic
#X3-beg    outflow
#X3-end    outflow

[Setup]
Sigma0      1
n           1

[Output]
vtk    2.0
dmp    100.0
log        1000
dmp_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/MyDustyWave/outputs/wave_n1
vtk_dir    /home/dp316/dp316/dc-fang1/IdefixRuns/MyDustyWave/outputs/wave_n1/vtks
# File produced automatically by a Perl script
# Do not edit
